{% set name = "SphericalTexture" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphericaltexture-{{ version }}.tar.gz
  sha256: 842f8f93d7d06ae8f079db1f92bd603b41e53c47da7ba5d7d6381d17e0843066

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core >=1.1.0
    - pip
  run:
    - python >=3.9
    - scikit-image
    - numba
    - pyshtools >=4.10.3
    - ducc0
    - scipy
    - appdirs

test:
  imports:
    - sphericaltexture
    # for now check pyshtools that way - pip check currently does not work
    # as pyshtools build seems to end up without .dist-info folder.
    # ref: https://github.com/conda-forge/pyshtools-feedstock/issues/62
    - pyshtools
  # commands:
  #   - python -m pip check
  # requires:
  #   - pip

about:
  summary: Angular projections of 2/3D image objects and subsequent spherical harmonics analysis
  license: MIT
  license_file: LICENSE
  home: https://github.com/KoehlerLab/SphericalTexture

extra:
  recipe-maintainers:
    - oanegros
