{% set name = "SphericalTexture" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphericaltexture-{{ version }}.tar.gz
  sha256: d8c34abffbc72b051d927d5ff52528760b22109e494e6620a71d839a9cf33309

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core >=1.1.0
    - pip
  run:
    - python >=3.9
    - scikit-image
    - numba
    - pyshtools ==4.10.3
    - ducc0
    - scipy
    - appdirs

test:
  imports:
    - sphericaltexture
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Angular projections of 2/3D image objects and subsequent spherical harmonics analysis
  license: MIT
  license_file: LICENSE
  home: https://github.com/KoehlerLab/SphericalTexture

extra:
  recipe-maintainers:
    - oanegros
